/*Questão 1*/
DELIMITER //
CREATE PROCEDURE SP_CALC_TOTAL_VENDAS(IN SP_DT_INICIAL DATE, IN SP_DT_FINAL DATE)
BEGIN
    DECLARE MAIS_LINHAS INT DEFAULT 0;
    DECLARE PRODUTO VARCHAR(150);
    DECLARE TOTAL DECIMAL(15,2); 
	DECLARE TOTAL_VENDAS DECIMAL(15,2);
    
    DECLARE MSG VARCHAR(150);

    DECLARE CUR CURSOR FOR SELECT P.NOME, SUM(IV.TOTAL)
    FROM ITENS_VENDA IV
    INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
    INNER JOIN PRODUTO P ON IV.ID_PRODUTO = P.ID_PRODUTO
    WHERE V.DATA_VENDA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL AND IV.TOTAL IS NOT NULL
    GROUP BY 1;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET MAIS_LINHAS = 1;
    SET MAIS_LINHAS = 0;

    DROP TEMPORARY TABLE IF EXISTS RESULTADO;
    CREATE TEMPORARY TABLE RESULTADO (
        PRODUTO VARCHAR(150),
        TOTAL DECIMAL(15,2),
        PERCENTUAL DECIMAL(15,2),
    );
	 
    SELECT SUM(IV.TOTAL) INTO TOTAL_VENDAS
    FROM ITENS_VENDA IV
    INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
    WHERE V.DATA_VENDA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL AND IV.TOTAL IS NOT NULL

    IF(TOTAL_VENDAS > 0) THEN
        OPEN CUR;
        LOOP_PROC: LOOP FETCH CUR INTO PRODUTO, TOTAL; 
            IF MAIS_LINHAS = 1 THEN
                LEAVE LOOP_PROC;
            END IF; 

            INSERT INTO RESULTADO (PRODUTO, TOTAL, PERCENTUAL)
            VALUES(PRODUTO, TOTAL, ((TOTAL * 100)/TOTAL_VENDAS));  
        END LOOP LOOP_PROC;    
        CLOSE CUR;

        SELECT *
        FROM RESULTADO;
    
        DROP TEMPORARY TABLE RESULTADO;  
    ELSE
        SET MSG = 'Total inválido!';
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG; 
    END IF; 
END;
// DELIMITER ;

/*Questão 1 - Incrementada*/
DELIMITER //
CREATE PROCEDURE SP_CALC_TOTAL_VENDAS(IN SP_DT_INICIAL DATE, IN SP_DT_FINAL DATE)
BEGIN
    DECLARE MAIS_LINHAS INT DEFAULT 0;
    DECLARE PRODUTO VARCHAR(150);
    DECLARE TOTAL DECIMAL(15,2); 
	DECLARE TOTAL_VENDAS DECIMAL(15,2);
    DECLARE PERCENTUAL DECIMAL(15,2);
    DECLARE PERC_ACUMULADO DECIMAL (15,2) DEFAULT 0;
    DECLARE TOTAL_ACUMULADO DECIMAL (15,2) DEFAULT 0;

    DECLARE MSG VARCHAR(150);

    DECLARE CUR CURSOR FOR SELECT P.NOME, SUM(IV.TOTAL)
    FROM ITENS_VENDA IV
    INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
    INNER JOIN PRODUTO P ON IV.ID_PRODUTO = P.ID_PRODUTO
    WHERE V.DATA_VENDA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL AND IV.TOTAL IS NOT NULL
    GROUP BY 1;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET MAIS_LINHAS = 1;
    SET MAIS_LINHAS = 0;

    DROP TEMPORARY TABLE IF EXISTS RESULTADO;
    CREATE TEMPORARY TABLE RESULTADO (
        PRODUTO VARCHAR(150),
        TOTAL DECIMAL(15,2),
        PERCENTUAL DECIMAL(15,2),
        PERC_ACUMULADO DECIMAL (15,2),
        TOTAL_ACUMULADO DECIMAL (15,2),
        TOTAL_VENDAS DECIMAL (15,2)
    );
	 
    SELECT SUM(IV.TOTAL) INTO TOTAL_VENDAS
    FROM ITENS_VENDA IV
    INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
    WHERE V.DATA_VENDA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL AND IV.TOTAL IS NOT NULL;

    IF(TOTAL_VENDAS > 0) THEN
        OPEN CUR;
        LOOP_PROC: LOOP FETCH CUR INTO PRODUTO, TOTAL; 
            IF MAIS_LINHAS = 1 THEN
                LEAVE LOOP_PROC;
            END IF; 

            SET PERCENTUAL = ((TOTAL * 100)/TOTAL_VENDAS);
            SET PERC_ACUMULADO = PERC_ACUMULADO + PERCENTUAL;
            SET TOTAL_ACUMULADO = TOTAL_ACUMULADO + TOTAL;

            INSERT INTO RESULTADO (PRODUTO, TOTAL, PERCENTUAL, PERC_ACUMULADO, TOTAL_ACUMULADO, TOTAL_VENDAS)
            VALUES(PRODUTO, TOTAL, PERCENTUAL, PERC_ACUMULADO, TOTAL_ACUMULADO, TOTAL_VENDAS);  
        END LOOP LOOP_PROC;    
        CLOSE CUR;

        SELECT *
        FROM RESULTADO;
    
        DROP TEMPORARY TABLE RESULTADO;  
    ELSE
        SET MSG = 'Total inválido!';
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG; 
    END IF; 
END;
// DELIMITER ;
 
/*Questão 2*/
DELIMITER //
CREATE PROCEDURE SP_CALC_TOTAL_VENDAS_E_COMPRAS(IN SP_DT_INICIAL DATE, IN SP_DT_FINAL DATE)
BEGIN 
    DECLARE MAIS_LINHAS INT DEFAULT 0;
    DECLARE ID_PROD INT;
    DECLARE NOME_PROD VARCHAR(150);
    DECLARE TOTAL_VENDA_PROD DECIMAL(15,2) DEFAULT 0;
    DECLARE TOTAL_COMPRA_PROD DECIMAL(15,2) DEFAULT 0;
    DECLARE PERC_VENDA_PROD DECIMAL(15,2) DEFAULT 0;
    DECLARE PERC_COMPRA_PROD DECIMAL(15,2) DEFAULT 0;
    DECLARE TOTAL_VENDAS DECIMAL(15,2) DEFAULT 0;
    DECLARE TOTAL_COMPRAS DECIMAL(15,2) DEFAULT 0;

    DECLARE CUR CURSOR FOR SELECT DISTINCT P.ID_PRODUTO, P.NOME
                            FROM PRODUTO P
                            WHERE P.ID_PRODUTO IN (SELECT DISTINCT IC.ID_PRODUTO
                                                FROM ITENS_COMPRA IC
                                                INNER JOIN COMPRA C ON IC.ID_COMPRA = C.ID_COMPRA
                                                WHERE C.DATA_COMPRA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL)
                            OR P.ID_PRODUTO IN (SELECT DISTINCT IV.ID_PRODUTO
                                                FROM ITENS_VENDA IV
                                                INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
                                                WHERE V.DATA_VENDA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL);
                                                
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET MAIS_LINHAS = 1;
    SET MAIS_LINHAS = 0;

    DROP TEMPORARY TABLE IF EXISTS RESULTADO;

    CREATE TEMPORARY TABLE RESULTADO (
        PRODUTO VARCHAR(60),
        TOTAL_COMPRADO DECIMAL(15,2),
        TOTAL_VENDIDO DECIMAL(15,2),
        PERC_COMPRA DECIMAL(15,2),
        PERC_VENDA DECIMAL(15,2)
    ); 

    SELECT SUM(IC.TOTAL) INTO TOTAL_COMPRAS
    FROM ITENS_COMPRA IC
    INNER JOIN COMPRA C ON IC.ID_COMPRA = C.ID_COMPRA
    WHERE C.DATA_COMPRA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL AND IC.TOTAL IS NOT NULL;

    SELECT SUM(IV.TOTAL) INTO TOTAL_VENDAS
    FROM ITENS_VENDA IV
    INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
    WHERE V.DATA_VENDA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL AND IV.TOTAL IS NOT NULL;

    OPEN CUR;
    LOOP_PROC: LOOP FETCH CUR INTO ID_PROD, NOME_PROD; 
        IF MAIS_LINHAS = 1 THEN
                LEAVE LOOP_PROC;
        END IF;  
        
        IF TOTAL_COMPRAS > 0 THEN
            SELECT DISTINCT 
            CASE 
                WHEN SUM(IC.TOTAL) IS NULL THEN 0 
                ELSE SUM(IC.TOTAL) 
            END AS TOTAL INTO TOTAL_COMPRA_PROD
            FROM ITENS_COMPRA IC
            INNER JOIN COMPRA C ON IC.ID_COMPRA = C.ID_COMPRA
            WHERE IC.ID_PRODUTO = ID_PROD
            AND C.DATA_COMPRA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL; 
 
            IF (TOTAL_COMPRA_PROD > 0) THEN 
                SET PERC_COMPRA_PROD = (TOTAL_COMPRA_PROD*100)/TOTAL_COMPRAS;
            ELSE 
                SET PERC_COMPRA_PROD = 0;
            END IF;    
        END IF;   

        IF TOTAL_VENDAS > 0 THEN
            SELECT DISTINCT 
            CASE 
				WHEN SUM(IV.TOTAL) IS NULL THEN 0 
                ELSE SUM(IV.TOTAL) 
			END AS TOTAL INTO TOTAL_VENDA_PROD
            FROM ITENS_VENDA IV
            INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
            WHERE IV.ID_PRODUTO = ID_PROD
            AND V.DATA_VENDA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL;

            IF (TOTAL_VENDA_PROD > 0) THEN 
                SET PERC_VENDA_PROD = (TOTAL_VENDA_PROD*100)/TOTAL_VENDAS;
            ELSE 
                SET PERC_VENDA_PROD = 0;
            END IF;
        END IF; 

        INSERT INTO RESULTADO (PRODUTO, TOTAL_COMPRADO, TOTAL_VENDIDO, PERC_COMPRA, PERC_VENDA)
        VALUES (NOME_PROD, TOTAL_COMPRA_PROD, TOTAL_VENDA_PROD, PERC_COMPRA_PROD, PERC_VENDA_PROD);
    END LOOP LOOP_PROC;    
    CLOSE CUR;

    SELECT *
    FROM RESULTADO;
    
    DROP TEMPORARY TABLE RESULTADO;  
END; 
// DELIMITER ;