CREATE VIEW V_SHOW_SOMATORIO_TOTAL (NOME_CLIENTE, TOTAL_COMPRAS) 
AS
SELECT C.NOME, SUM(V.TOTAL)
FROM VENDA V
INNER JOIN CLIENTE C ON V.ID_CLIENTE = C.ID_CLIENTE
WHERE YEAR(V.DATA_VENDA) = 2020
GROUP BY V.ID_CLIENTE
ORDER BY 2 DESC;

CREATE VIEW V_SHOW_TOP_PRODUTOS (PRODUTO, QUANTIDADE)
AS
SELECT P.NOME, SUM(IV.QUANTIDADE)
FROM ITENS_VENDA IV
INNER JOIN PRODUTO P ON IV.ID_PRODUTO = P.ID_PRODUTO
INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
WHERE MONTH(V.DATA_VENDA) = 8 AND YEAR(V.DATA_VENDA) = 2020
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

DELIMITER //
CREATE PROCEDURE SP_ATUALIZA_ESTOQUE_VENDA(IN ID_VENDA_PROC INT)
BEGIN
	DECLARE MAIS_LINHAS INT DEFAULT 0;
	DECLARE ID_PROD_PROC INT;
	DECLARE QUANT DECIMAL(15,2);
	
	DECLARE CUR CURSOR FOR SELECT IV.ID_PRODUTO, IV.QUANTIDADE
	FROM ITENS_VENDA IV
	WHERE IV.ID_VENDA = ID_VENDA_PROC;
	
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET MAIS_LINHAS = 1;
	SET MAIS_LINHAS = 0;
	
	OPEN CUR;
	LOOP_PROC: LOOP FETCH CUR INTO ID_PROD_PROC, QUANT;
		IF MAIS_LINHAS = 1 THEN
			LEAVE LOOP_PROC;
		END IF;
		
		UPDATE PRODUTO P
		SET P.QUANT_ATUAL = P.QUANT_ATUAL-QUANT
		WHERE P.ID_PRODUTO = ID_PROD_PROC;
	END LOOP LOOP_PROC;
END;
// DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_ATUALIZA_ESTOQUE_COMPRA(IN ID_COMPRA_PROC INT)
BEGIN
	DECLARE MAIS_LINHAS INT DEFAULT 0;
	DECLARE ID_PROD_PROC INT;
	DECLARE QUANT DECIMAL(15,2);
	
	DECLARE CUR CURSOR FOR SELECT IC.ID_PRODUTO, IC.QUANTIDADE
	FROM ITENS_COMPRA IC
	WHERE IC.ID_COMPRA = ID_COMPRA_PROC;
	
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET MAIS_LINHAS = 1;
	SET MAIS_LINHAS = 0;
	
	OPEN CUR;
	LOOP_PROC: LOOP FETCH CUR INTO ID_PROD_PROC, QUANT;
		IF MAIS_LINHAS = 1 THEN
			LEAVE LOOP_PROC;
		END IF;
		
		UPDATE PRODUTO P
		SET P.QUANT_ATUAL = P.QUANT_ATUAL+QUANT
		WHERE P.ID_PRODUTO = ID_PROD_PROC;
	END LOOP LOOP_PROC;
END;
// DELIMITER ;


DELIMITER //
CREATE PROCEDURE SP_INSERE_HISTORICO(IN ID_PROD_PROC INT, IN ID_COMPRA_VENDA INT, IN NOME_TABELA CHAR(1), IN OP CHAR(1), IN QTD DECIMAL(15,2), IN VALOR DECIMAL(15,2))
BEGIN
	IF NOME_TABELA = 'V' THEN
		INSERT INTO HISTORICO_ESTOQUE (ID_PRODUTO, ID_VENDA, QUANTIDADE, VALOR_UNIT, TOTAL, OPERACAO, DATA_OPERACAO)
		VALUES (ID_PROD_PROC, ID_COMPRA_VENDA, QTD, VALOR, (QTD*VALOR), OP, CURDATE());
	ELSEIF NOME_TABELA = 'C' THEN
		INSERT INTO HISTORICO_ESTOQUE (ID_PRODUTO, ID_COMPRA, QUANTIDADE, VALOR_UNIT, TOTAL, OPERACAO, DATA_OPERACAO)
		VALUES (ID_PROD_PROC, ID_COMPRA_VENDA, QTD, VALOR, (QTD*VALOR), OP, CURDATE());
	ELSE
		INSERT INTO HISTORICO_ESTOQUE (ID_PRODUTO, QUANTIDADE, VALOR_UNIT, TOTAL, OPERACAO, DATA_OPERACAO)
		VALUES (ID_PROD_PROC, QTD, VALOR, (QTD*VALOR), OP, CURDATE());
	END IF;
END;
// DELIMITER ;