DELIMITER //
CREATE PROCEDURE SP_ATUALIZA_COMPRA()
BEGIN
	DECLARE MAIS_LINHAS INT DEFAULT 0;
	DECLARE ID_COMPRA INT;
    DECLARE ID_FORNEC INT;
		
    DECLARE CUR CURSOR FOR SELECT C.ID_COMPRA, C.ID_FORNEC
    FROM COMPRA C;
    
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET MAIS_LINHAS=1;
    SET MAIS_LINHAS = 0;
    
    OPEN CUR;
    LOOP_CUR: LOOP FETCH CUR INTO ID_COMPRA, ID_FORNEC;
		IF MAIS_LINHAS = 1 THEN
			LEAVE LOOP_CUR;
        END IF; 
        
        UPDATE COMPRA C SET C.TOTAL = C.SUB_TOTAL-C.DESCONTO
        WHERE C.ID_COMPRA = ID_COMPRA AND C.ID_FORNEC = ID_FORNEC; 
        
    END LOOP LOOP_CUR;
    CLOSE CUR; 
END;
// DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_ATUALIZA_VENDA()
BEGIN
	DECLARE MAIS_LINHAS INT DEFAULT 0;
	DECLARE ID_VENDA INT;
    DECLARE ID_CLIENTE INT;
		
    DECLARE CUR CURSOR FOR SELECT V.ID_VENDA, V.ID_CLIENTE
    FROM VENDA V;
    
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET MAIS_LINHAS=1;
    SET MAIS_LINHAS = 0;
    
    OPEN CUR;
    LOOP_CUR: LOOP FETCH CUR INTO ID_VENDA, ID_CLIENTE;
		IF MAIS_LINHAS = 1 THEN
			LEAVE LOOP_CUR;
        END IF; 
        
        UPDATE VENDA V SET V.TOTAL = V.SUB_TOTAL-V.DESCONTO
        WHERE V.ID_VENDA = ID_VENDA AND V.ID_CLIENTE = ID_CLIENTE; 
        
    END LOOP LOOP_CUR;
    CLOSE CUR; 
END;
// DELIMITER ;