/*Calcula o desconto com base no número de vendas do cliente*/
DELIMITER // 
CREATE TRIGGER T_CALCULA_DESCONTO_VENDA_BI
BEFORE INSERT ON VENDA
FOR EACH ROW
BEGIN
	DECLARE QTD_VENDAS INT;
	
	SELECT C.NUMERO_VENDAS INTO QTD_VENDAS
	FROM CLIENTE C
	WHERE C.ID_CLIENTE = NEW.ID_CLIENTE;
	
	IF (QTD_VENDAS >= 2 AND QTD_VENDAS <= 9) THEN
		SET NEW.DESCONTO = 5;
	ELSEIF (QTD_VENDAS >= 10 AND QTD_VENDAS <= 24) THEN
		SET NEW.DESCONTO  = 10;
	ELSEIF (QTD_VENDAS >= 25 AND QTD_VENDAS <= 36) THEN
		SET NEW.DESCONTO = 15;
	ELSEIF (QTD_VENDAS > 36) THEN
		SET NEW.DESCONTO = 20;
	ELSE
		SET NEW.DESCONTO = 0;
	END IF;
END;
//DELIMITER ;