#ATIVIDADE 8 testes

DELIMITER //
CREATE PROCEDURE SP_CALC_TOTAL_VENDAS(IN SP_DT_INICIAL DATE, IN SP_DT_FINAL DATE)
BEGIN
	DECLARE TOTAL_VENDAS DECIMAL(15,2);
    
    SELECT SUM(IV.TOTAL) INTO TOTAL_VENDAS
    FROM ITENS_VENDA IV
    INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
    WHERE V.DATA_VENDA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL; 
	
    SELECT P.NOME AS 'Produto', SUM(IV.TOTAL) AS 'Total Produto', ((SUM(IV.TOTAL) * 100)/TOTAL_VENDAS) AS 'Porcentagem'
    FROM ITENS_VENDA IV
    INNER JOIN PRODUTO P ON IV.ID_PRODUTO = P.ID_PRODUTO
    INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
    WHERE V.DATA_VENDA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL AND IV.TOTAL IS NOT NULL
    GROUP BY 1;
END;
// DELIMITER ;


/*com o uso de cursor*/
DELIMITER //
CREATE PROCEDURE SP_CALC_TOTAL_VENDAS(IN SP_DT_INICIAL DATE, IN SP_DT_FINAL DATE)
BEGIN
    DECLARE MAIS_LINHAS INT DEFAULT 0;
    DECLARE PRODUTO VARCHAR(150);
    DECLARE TOTAL DECIMAL(15,2); 

	DECLARE TOTAL_VENDAS DECIMAL(15,2);
    
    DECLARE CUR CURSOR FOR SELECT P.NOME, SUM(IV.TOTAL)
    FROM ITENS_VENDA IV
    INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
    INNER JOIN PRODUTO P ON IV.ID_PRODUTO = P.ID_PRODUTO
    WHERE V.DATA_VENDA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL AND IV.TOTAL IS NOT NULL
    GROUP BY 1;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET MAIS_LINHAS = 1;
    SET MAIS_LINHAS = 0;

    CREATE TEMPORARY TABLE RESULTADO (
        PRODUTO VARCHAR(150),
        TOTAL DECIMAL(15,2),
        PERCENTUAL DECIMAL(15,2)
    );
	 
    SELECT SUM(IV.TOTAL) INTO TOTAL_VENDAS
    FROM ITENS_VENDA IV
    INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
    WHERE V.DATA_VENDA BETWEEN SP_DT_INICIAL AND SP_DT_FINAL; 

    OPEN CUR;
    LOOP_PROC: LOOP FETCH CUR INTO PRODUTO, TOTAL; 
		IF MAIS_LINHAS = 1 THEN
            LEAVE LOOP_PROC;
        END IF;    
        INSERT INTO RESULTADO (PRODUTO, TOTAL, PERCENTUAL)
        VALUES(PRODUTO, TOTAL, ((TOTAL * 100)/TOTAL_VENDAS));
    END LOOP LOOP_PROC;    
    CLOSE CUR;

    SELECT *
    FROM RESULTADO;
 
    DROP TEMPORARY TABLE RESULTADO; 
END;
// DELIMITER ;



CALL SP_CALC_TOTAL_VENDAS('2020-03-12', '2020-12-22');

DROP PROCEDURE SP_CALC_TOTAL_VENDAS;
DROP TEMPORARY TABLE RESULTADO; 

SELECT SUM(IV.TOTAL)
FROM ITENS_VENDA IV
INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
WHERE V.DATA_VENDA BETWEEN '2020-03-12' and '2020-12-22' AND IV.TOTAL IS NOT NULL;

SELECT P.NOME AS 'Produto', SUM(IV.TOTAL) AS 'Total Produto'
FROM ITENS_VENDA IV
INNER JOIN PRODUTO P ON IV.ID_PRODUTO = P.ID_PRODUTO
INNER JOIN VENDA V ON IV.ID_VENDA = V.ID_VENDA
WHERE V.DATA_VENDA BETWEEN '2020-03-12' and '2020-12-22' AND IV.TOTAL IS NOT NULL
GROUP BY 1;